# Generated by Django 4.0.5 on 2022-06-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('product_detail', models.TextField()),
                ('product_barcode', models.CharField(max_length=13)),
                ('product_qty', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product_image', models.CharField(max_length=128)),
                ('product_status', models.IntegerField()),
            ],
        ),
    ]
